-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 15:00:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Serv+Cuscuz` DEFAULT CHARACTER SET utf8 ;
USE `Serv+Cuscuz` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `senha` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `email_2` (`email` ASC),
  UNIQUE INDEX `cpf_2` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


--
-- Despejando dados para a tabela `t_cliente`
--

INSERT INTO `t_cliente` (`id`, `nome`, `sobrenome`, `cpf`, `email`, `telefone`, `data_criacao`, `data_atualizacao`, `senha`) VALUES
(0, 'denilson', 'salazar', '12345678978', 'denilson@gmail.com', '12345678973', '2024-10-22 15:25:28', '2024-10-22 15:25:28', '$2y$10$owLMFWaYGckvgf4FOeVqXezLx8EPRAp6fTORyHr69jEHGNI8dIkha');



-- -----------------------------------------------------
-- Table `mydb`.`t_alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_alergia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_alergia` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `t_cliente_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_alergia_t_cliente1_idx` (`t_cliente_id1` ASC),
  CONSTRAINT `fk_t_alergia_t_cliente1`
    FOREIGN KEY (`t_cliente_id1`)
    REFERENCES `mydb`.`t_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_endereco` (
  `id` INT(14) NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `t_cliente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cliente_idx` (`t_cliente_id` ASC),
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`t_cliente_id`)
    REFERENCES `mydb`.`t_cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_perfil` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_perfil` ENUM('FUNCIONARIO', 'ADMINISTRADOR') CHARACTER SET 'armscii8' NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

--
-- Despejando dados para a tabela `t_perfil`
--

INSERT INTO `t_perfil` (`id`, `tipo_perfil`, `descricao`) VALUES
(1, 'ADMINISTRADOR', 'Perfil com acesso a funcionalidades administrativas.'),
(2, 'FUNCIONARIO', 'Perfil do funcionário');


-- -----------------------------------------------------
-- Table `mydb`.`t_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `data_criacao` DATE NULL DEFAULT NULL,
  `senha` VARCHAR(50) NULL DEFAULT NULL,
  `t_perfil_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `email_2` (`email` ASC),
  INDEX `fk_t_funcionario_t_perfil1_idx` (`t_perfil_id1` ASC),
  CONSTRAINT `fk_t_funcionario_t_perfil1`
    FOREIGN KEY (`t_perfil_id1`)
    REFERENCES `mydb`.`t_perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

--
-- Despejando dados para a tabela `t_funcionario`
--

INSERT INTO `t_funcionario` (`id`, `nome`, `cpf`, `email`, `telefone`, `data_criacao`, `senha`, `t_perfil_id`) VALUES
(0, 'Funcionario', '12345678912', 'funcionario@gmail.com', '12345678912', NULL, '$2y$10$pPizy0yB1q1e8WzvNgBA5.9aNgzw4aBYL72GApAbgGixPIGg.pkbW', 2),
(1, 'Administrador', '01234567891', 'administrador@gmail.com', '01234567890', NULL, '$2y$10$wOcJ2sJnt0u06j3CDBu0Iur/guqaFYbvPYsEl3CR1avH.KCAOg/7i', 1);

-- -----------------------------------------------------
-- Table `mydb`.`t_ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_ingrediente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco_adicional` DECIMAL(10,2) NULL DEFAULT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `imagem` LONGBLOB NULL DEFAULT NULL,
  `estoque` INT(11) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `personalizavel` TINYINT(1) NULL DEFAULT NULL,
  `tipo_personalizacao` VARCHAR(50) NULL DEFAULT NULL,
  `descricao_personalizacao` TEXT NULL DEFAULT NULL,
  `unidade_medida` VARCHAR(50) NULL DEFAULT NULL,
  `disponivel` TINYINT(1) NULL DEFAULT NULL,
  `t_funcionario_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_funcionario_idx` (`t_funcionario_id` ASC),
  CONSTRAINT `fk_produto_funcionario`
    FOREIGN KEY (`t_funcionario_id`)
    REFERENCES `mydb`.`t_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `status` ENUM('PENDENTE', 'EM_PREPARO', 'A_CAMINHO', 'ENTREGUE', 'CANCELADO') NULL DEFAULT NULL,
  `entrega_domicilio` TINYINT(1) NULL DEFAULT NULL,
  `t_cliente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `T_Cliente_id` (`t_cliente_id` ASC),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`t_cliente_id`)
    REFERENCES `mydb`.`t_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_itemPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_itemPedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `valor_unitario` DECIMAL(10,2) NULL DEFAULT NULL,
  `preco_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `t_pedido_id` INT(11) NOT NULL,
  `t_produto_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `T_Pedido_id` (`t_pedido_id` ASC),
  INDEX `T_Produto_id` (`t_produto_id` ASC),
  CONSTRAINT `fk_itemPedido_produto`
    FOREIGN KEY (`t_produto_id`)
    REFERENCES `mydb`.`t_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemPedido_pedido`
    FOREIGN KEY (`t_pedido_id`)
    REFERENCES `mydb`.`t_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_opcaoAdicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_opcaoAdicional` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_itemPedidoOpcaoAdicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_itemPedidoOpcaoAdicional` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `t_itemPedido_id` INT(11) NOT NULL,
  `t_opcaoAdicional_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `T_ItemPedido_id` (`t_itemPedido_id` ASC),
  INDEX `T_OpcaoAdicional_id` (`t_opcaoAdicional_id` ASC),
  CONSTRAINT `fk_ItemPedidoOpcaoAdicional_itemPedido`
    FOREIGN KEY (`t_itemPedido_id`)
    REFERENCES `mydb`.`t_itemPedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPedidoOpcaoAdicional_opcaoAdicional`
    FOREIGN KEY (`t_opcaoAdicional_id`)
    REFERENCES `mydb`.`t_opcaoAdicional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_pagamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `status_pagamento` ENUM('PENDENTE', 'APROVADO', 'REJEITADO') NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(50) NULL DEFAULT NULL,
  `t_pedido_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_pagamento_t_pedido1_idx` (`t_pedido_id1` ASC),
  CONSTRAINT `fk_t_pagamento_t_pedido1`
    FOREIGN KEY (`t_pedido_id1`)
    REFERENCES `mydb`.`t_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_personalizacaoProdutoIngrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_personalizacaoProdutoIngrediente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `obrigatorio` TINYINT(1) NULL DEFAULT NULL,
  `preco_unidade` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantidade_padrao` INT(11) NULL DEFAULT NULL,
  `quantidade_minima` INT(11) NULL DEFAULT NULL,
  `quantidade_maxima` INT(11) NULL DEFAULT NULL,
  `t_produto_id` INT(11) NOT NULL,
  `t_ingrediente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personalizacaoProdutoIngrediente_produto_idx` (`t_produto_id` ASC),
  INDEX `fk_personalizacaoProdutoIngrediente_Ingrediente_idx` (`t_ingrediente_id` ASC),
  CONSTRAINT `fk_personalizacaoProdutoIngrediente_produto`
    FOREIGN KEY (`t_produto_id`)
    REFERENCES `mydb`.`t_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personalizacaoProdutoIngrediente_Ingrediente`
    FOREIGN KEY (`t_ingrediente_id`)
    REFERENCES `mydb`.`t_ingrediente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`t_promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_promocao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `desconto` DECIMAL(10,2) NULL DEFAULT NULL,
  `tipo_promocao` VARCHAR(50) NULL DEFAULT NULL,
  `condição_promocao` TEXT NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `campo_porcentagem` TINYINT(1) NULL DEFAULT NULL,
  `t_produto_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `T_Produto_id` (`t_produto_id` ASC),
  CONSTRAINT `fk_promocao_produto`
    FOREIGN KEY (`t_produto_id`)
    REFERENCES `mydb`.`t_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
